
{{- range $roleName, $role := .Values.vmRoles }}
{{- range $index := until ($role.count | int) }}

{{- $disk_boot_image := index (default (dict) $role.storage) "boot_image_url" | default $.Values.storage.golden_boot_image.url -}}
{{- $hostName := printf "%s-%d" $roleName  $index -}}

{{- $cloudInitUserData := index (default (dict) $role.cloudInit) "userData" | default (index (default (dict) $.Values.cloudInit) "userData") -}}
{{- $cloudInitNetworkData := index (default (dict) $role.cloudInit) "networkData" | default (index (default (dict) $.Values.cloudInit) "networkData") -}}
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: {{ $hostName }}
spec:
  running: true
  template:
    metadata:
      labels:
        {{- include "kubevirtVM.labels" $ | nindent 8 }}
        role: {{ $roleName }}
        hostname: {{ $hostName }}
        {{- if not $role.hostDisk }}
        state: "Stateless"
        {{- else }}
        state: "Stateful"
        {{- end }}
    spec:
      {{- if $role.hostDisk }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    {{- include "kubevirtVM.selectorLabels" $ | nindent 20 }}
      {{- end }}
      hostname: {{ $hostName }}
      domain:
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            {{- if $role.hostDisk }}
            - name: workdir
              disk:
                bus: virtio
            {{- end }}
            {{- if or $cloudInitUserData $cloudInitNetworkData }}
            - name: cloudinitdisk
              disk:
                bus: virtio
            {{- end }}
          interfaces:
            - bridge: {}
              name: bar
          networkInterfaceMultiqueue: true
{{- with $role.resources }}
        resources:
{{ toYaml . | indent 10 }}
{{- end }}
      networks:
        - name: bar
          multus:
            networkName: bridge
      volumes:
        - name: rootdisk
          containerDisk:
            image: {{ $disk_boot_image | quote }}
        {{- if $role.hostDisk }}
        - name: workdir
          hostDisk:
            capacity: {{ $role.hostDisk.capacity }}
            path: /var/hostdisk/{{ $hostName }}.img
            type: DiskOrCreate
        {{- end }}
        {{- if or $cloudInitUserData $cloudInitNetworkData }}
        - name: cloudinitdisk
          cloudInitNoCloud:
            {{- if $cloudInitUserData }}
            userData: |
              {{- $cloudInitUserData | trim | nindent 17 -}}
            {{- end }}
            {{ if $cloudInitNetworkData -}}
            networkData: |
              {{- $cloudInitNetworkData | nindent 17 }}
            {{ end -}}
        {{- end }}
{{ end }}
{{ end }}
