
{{- range $roleName, $role := .Values.vmRoles }}
{{- range $index := until ($role.count | int) }}

{{- $disk_boot_image := index (default (dict) $role.storage) "boot_image_url" | default $.Values.storage.golden_boot_image.url -}}

{{- $cloudInitUserData := index (default (dict) $role.cloudInit) "userData" | default (index (default (dict) $.Values.cloudInit) "userData") -}}
{{- $cloudInitNetworkData := index (default (dict) $role.cloudInit) "networkData" | default (index (default (dict) $.Values.cloudInit) "networkData") -}}
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: {{ $roleName }}-{{ $index }}
spec:
  running: true
  template:
    metadata:
      labels:
        label: "TODO"
    spec:
      hostname: {{ $roleName }}-{{ $index }}
      domain:
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            {{- if $role.hostDisk }}
            - name: workdir
              disk:
                bus: virtio
            {{- end }}
            {{- if or $cloudInitUserData $cloudInitNetworkData }}
            - name: cloudinitdisk
              disk:
                bus: virtio
            {{- end }}
          interfaces:
            - bridge: {}
              name: bar
          networkInterfaceMultiqueue: true
{{- with $role.resources }}
        resources:
{{ toYaml . | indent 10 }}
{{- end }}
      networks:
        - name: bar
          multus:
            networkName: bridge
      volumes:
        - name: rootdisk
          containerDisk:
            image: {{ $disk_boot_image | quote }}
        {{- if $role.hostDisk }}
        - name: workdir
          hostDisk:
            capacity: {{ $role.hostDisk.capacity }}
            path: /var/hostdisk/{{ $roleName }}-{{ $index }}.img
            type: DiskOrCreate
        {{- end }}
        {{- if or $cloudInitUserData $cloudInitNetworkData }}
        - name: cloudinitdisk
          cloudInitNoCloud:
            {{- if $cloudInitUserData }}
            userData: |
              {{- $cloudInitUserData | trim | nindent 17 -}}
            {{- end }}
            {{ if $cloudInitNetworkData -}}
            networkData: |
              {{- $cloudInitNetworkData | nindent 17 }}
            {{ end -}}
        {{- end }}
{{ end }}
{{ end }}
