{{- range $flavorName, $flavor := .Values.flavors }}
---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstancePreset
metadata:
  name: {{ $flavorName }}
spec:
  selector:
    matchLabels:
      role: {{ $flavor.role }}
  domain:
    resources:
      requests:
        {{- if $flavor.memory }}
        memory: {{ $flavor.memory }}
        {{- end }}
        {{- if $flavor.cpu }}
        cpu: {{ $flavor.cpu }}
        {{- end }}
{{ end }}
