vmRoles:
  master:
    count: 1
#    boot_image_url: "custom_specific_image"
    resources:
      requests:
        memory: 1G
        cpu: "1"

  worker:
    count: 2
    resources:
      requests:
        memory: 1G
        cpu: "1"




storage:
  golden_boot_image:
    url: "quay.io/kubevirt/virtio-container-disk:v0.36.4"
