vmRoles:
#  master:
#    count: 1
##    boot_image_url: "custom_specific_image"
#    resources:
#      requests:
#        memory: 1G
#        cpu: "1"

  worker:
    count: 1
    resources:
      requests:
        memory: 1G
        cpu: "1"
    cloudInit:
      userData: |
        name: vasya

  database:
    count: 1
    resources:
      requests:
        memory: 1G
    hostDisk:
      capacity: 1Gi
    cloudInit:
      networkData: |
        version: 2
        ethernets:
          # opaque ID for physical interfaces, only referred to by other stanzas
          enp1s0:
            addresses:
              - 192.168.50.2/24
            gateway4: 192.168.50.1
            nameservers:
              addresses: [8.8.8.8]

cloudInit:
  userData: |
    ssh_authorized_keys:
      - TBD

storage:
  golden_boot_image:
    url: "quay.io/kubevirt/virtio-container-disk:v0.36.4"
