vmRoles:
#  master:
#    count: 1
##    boot_image_url: "custom_specific_image"
#    resources:
#      requests:
#        memory: 1G
#        cpu: "1"

  worker:
    count: 1
    resources:
      requests:
        memory: 1G
        cpu: "1"
    cloudInit:
      userData: |
        name: vasya

  database:
    count: 1
    hostDisk:
      capacity: 1Gi


cloudInit:
  userData: |
    ssh_authorized_keys:
      - TBD

storage:
  golden_boot_image:
    url: "quay.io/kubevirt/virtio-container-disk:v0.36.4"
